[package]
name = "chess-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-lib = { path = "../chess-lib" }
clap = { version = "4.0.26", features = ["derive"] }
colored = "2.0.0"
